name: Azure Data Factory CI/CD Pipeline

on:
  push:
    branches: ["adf_publish"]


jobs:
  # Continuous Integration (CI) Stage
  build:
    runs-on: self-hosted

    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

  
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4.4.2
      with:
        name: ExportedArmTemplate
        path: ${{ github.workspace }}
    
      

  # Continuous Deployment (CD) Stage
  release:
    needs: build
    runs-on: self-hosted
    environment: production

    steps:
    - name: Download Build Artifact
      uses: actions/download-artifact@v4.1.8
      with:
        name: ExportedArmTemplate

            
    - name: Azure Login
      uses: azure/login@v2.2.0
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        environment: AzureCloud
        audience: api://AzureADTokenExchange
        auth-type: SERVICE_PRINCIPAL

    - name: Azure PowerShell Pre-deployment
      uses: Azure/powershell@v2
      with:
        inlineScript: ${{ github.workspace }}\pre_post_deployment.ps1 -armTemplate "${{ github.workspace }}\ARMTemplateForFactory.json" -ResourceGroupName Anupam_rg -DataFactoryName prod-datafactory11 -predeployment $true -deleteDeployment $false
        azPSVersion: "latest"
        errorActionPreference: Stop

    - name: Deploy Azure Resource Manager (ARM) Template
      uses: Azure/arm-deploy@v2
      with:
        scope: 'resourcegroup'
        subscriptionId: '99705b85-b557-494c-bc4b-73e0ca27df77'
        resourceGroupName: 'Anupam_rg'
        template: ${{ github.workspace }}\ARMTemplateForFactory.json
        parameters: ${{ github.workspace }}\ARMTemplateParametersForFactory.json
        deploymentMode: Incremental
        deploymentName: adf-deployment
        additionalArguments: |
          -p factoryName=prod-datafactory11
          -p linkserviceAzureBlobStorage1_properties_typeProperties_serviceEndpoint="https://prodstg1232123.blob.core.windows.net/"

    - name: Azure PowerShell Post-deployment
      uses: Azure/powershell@v1
      with:
        inlineScript: ${{ github.workspace }}\pre_post_deployment.ps1 -armTemplate "${{ github.workspace }}\ARMTemplateForFactory.json" -ResourceGroupName Anupam_rg -DataFactoryName prod-datafactory11 -predeployment $false -deleteDeployment $true
        azPSVersion: "latest"
        errorActionPreference: Stop
