name: Azure Data Factory CI/CD Pipeline

on:
  push:
    branches: ["adf_publish"]
  workflow_dispatch:
  
    
jobs:
  # Continuous Integration (CI) Stage
  build:
    runs-on: self-hosted
    # defaults:
    #   run:
    #     working-directory: ./adf_publish/

    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        ref: adf_publish 
        


  
    - name: Upload Build Artifact
      uses: actions/upload-artifact@v4.4.2
      with:
        name: ExportedArmTemplate
        path: ${{ github.workspace }}
    
      

  # Continuous Deployment (CD) Stage
  release:
    needs: build
    runs-on: self-hosted
    environment: production

    steps:
    - name: Download Build Artifact
      uses: actions/download-artifact@v4.1.8
      with:
        name: ExportedArmTemplate


        
    - name: Checkout Repository
      uses: actions/checkout@v3
      with:
        ref: adf_publish 

        
        
    - name: List Files in Workspace
      run: |
        Get-ChildItem -Recurse | Select-Object FullName

    - name: Azure Login
      uses: azure/login@v2.2.0
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        environment: AzureCloud
        enble-AzPSSession: true
        # audience: api://AzureADTokenExchange
        # auth-type: SERVICE_PRINCIPAL

    - name: Azure PowerShell Pre-deployment
      shell: powershell
      run: |
        # # Parse the JSON secret
        # $credentialsJson = "${{ secrets.AZURE_CREDENTIALS }}"
        # $creds = $credentialsJson | ConvertFrom-Json
    
        # # Extract values
        # $clientId = "7ba1657d-ab36-4b28-b016-57ed4092be2f"
        # $tenantId = "e4e34038-ea1f-4882-b6e8-ccd776459ca0"
        # $clientSecret = "RM28Q~J9sXPb0qx49HWsk4ZE7My2ds3KSAQiaaQL"
    
        # # Convert client secret to a secure string
        # $securePassword = ConvertTo-SecureString $clientSecret -AsPlainText -Force
    
        # # Create a credential object
        # $credential = New-Object System.Management.Automation.PSCredential ($clientId, $securePassword)
    
        # # Log in to Azure using the service principal
        # Connect-AzAccount -ServicePrincipal -Credential $credential -TenantId $tenantId

        $armTemplate = 'C:\Users\Administrator\actions-runner\_work\adfcopyrepo\adfcopyrepo\adf-dev-test123321\ARMTemplateForFactory.json'
        $resourceGroupName = 'Anupam_rg'
        $dataFactoryName = 'prod-datafactory11'
        & 'C:\Users\Administrator\actions-runner\_work\adfcopyrepo\adfcopyrepo\adf-dev-test123321\pre_post_deployment.ps1' -armTemplate $armTemplate -ResourceGroupName $resourceGroupName -DataFactoryName $dataFactoryName -predeployment $true -deleteDeployment $false



    # - name: Azure PowerShell Pre-deployment
    #   shell: powershell 
    #   run: powershell -Command "C:\Users\Administrator\actions-runner\_work\adfcopyrepo\adfcopyrepo\adf-dev-test123321\pre_post_deployment.ps1 -armTemplate 'C:\Users\Administrator\actions-runner\_work\adfcopyrepo\adfcopyrepo\adf-dev-test123321\ARMTemplateForFactory.json' -ResourceGroupName 'Anupam_rg' -DataFactoryName 'prod-datafactory11' -predeployment:$true -deleteDeployment:$false"
      # uses: Azure/powershell@v2
      # with:
      #   inlineScript: |
      #     & 'C:\Users\Administrator\actions-runner\_work\adfcopyrepo\adfcopyrepo\adf-dev-test123321\pre_post_deployment.ps1' -armTemplate 'C:\Users\Administrator\actions-runner\_work\adfcopyrepo\adfcopyrepo\adf-dev-test123321\ARMTemplateForFactory.json' -ResourceGroupName Anupam_rg -DataFactoryName prod-datafactory11 -predeployment $true -deleteDeployment $false
      #   azPSVersion: "latest"
      #   errorActionPreference: Stop

    
    - name: Deploy Azure Resource Manager (ARM) Template
      uses: Azure/arm-deploy@v2
      with:
        scope: 'resourcegroup'
        subscriptionId: '99705b85-b557-494c-bc4b-73e0ca27df77'
        resourceGroupName: 'Anupam_rg'
        template: "${{ github.workspace }}/adf-dev-test123321/ARMTemplateForFactory.json"
        parameters: "${{ github.workspace }}/adf-dev-test123321/ARMTemplateParametersForFactory.json"
        deploymentMode: Incremental
        deploymentName: adf-deployment
        additionalArguments: |
          -p factoryName=prod-datafactory11
          -p linkserviceAzureBlobStorage1_properties_typeProperties_serviceEndpoint="https://prodstg1232123.blob.core.windows.net/"



    - name: Azure PowerShell Pre-deployment
      shell: powershell
      run: |
        $armTemplate = 'C:\Users\Administrator\actions-runner\_work\adfcopyrepo\adfcopyrepo\adf-dev-test123321\ARMTemplateForFactory.json'
        $resourceGroupName = 'Anupam_rg'
        $dataFactoryName = 'prod-datafactory11'
        & 'C:\Users\Administrator\actions-runner\_work\adfcopyrepo\adfcopyrepo\adf-dev-test123321\pre_post_deployment.ps1' -armTemplate $armTemplate -ResourceGroupName $resourceGroupName -DataFactoryName $dataFactoryName -predeployment $false -deleteDeployment $true
    
    # - name: Azure PowerShell Post-deployment
    #   uses: Azure/powershell@v1
    #   with:
    #     inlineScript: |
    #       & 'C:\Users\Administrator\actions-runner\_work\adfcopyrepo\adfcopyrepo\adf-dev-test123321\pre_post_deployment.ps1' -armTemplate 'C:\Users\Administrator\actions-runner\_work\adfcopyrepo\adfcopyrepo\adf-dev-test123321\ARMTemplateForFactory.json' -ResourceGroupName Anupam_rg -DataFactoryName prod-datafactory11 -predeployment $false -deleteDeployment $true
    #     azPSVersion: "latest"
    #     errorActionPreference: Stop


      


    # - name: Azure PowerShell Pre-deployment
    #   uses: Azure/powershell@v2
    #   with:
    #     inlineScript: .\adf-dev-test123321\pre_post_deployment.ps1 -armTemplate ".\ARMTemplateForFactory.json" -ResourceGroupName Anupam_rg -DataFactoryName prod-datafactory11 -predeployment $true -deleteDeployment $false
    #     azPSVersion: "latest"
    #     errorActionPreference: Stop

    # - name: Deploy Azure Resource Manager (ARM) Template
    #   uses: Azure/arm-deploy@v2
    #   with:
    #     scope: 'resourcegroup'
    #     subscriptionId: '99705b85-b557-494c-bc4b-73e0ca27df77'
    #     resourceGroupName: 'Anupam_rg'
    #     template: .\ARMTemplateForFactory.json
    #     parameters: .\ARMTemplateParametersForFactory.json
    #     deploymentMode: Incremental
    #     deploymentName: adf-deployment
    #     additionalArguments: |
    #       -p factoryName=prod-datafactory11
    #       -p linkserviceAzureBlobStorage1_properties_typeProperties_serviceEndpoint="https://prodstg1232123.blob.core.windows.net/"

    # - name: Azure PowerShell Post-deployment
    #   uses: Azure/powershell@v1
    #   with:
    #     inlineScript: ${{ github.workspace }}\pre_post_deployment.ps1 -armTemplate "${{ github.workspace }}\ARMTemplateForFactory.json" -ResourceGroupName Anupam_rg -DataFactoryName prod-datafactory11 -predeployment $false -deleteDeployment $true
    #     azPSVersion: "latest"
    #     errorActionPreference: Stop
