name: learn-github-actions

on: [push]

jobs:
  setup-python:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.4


      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Databricks CLI
        run: |
          python -m pip install --upgrade pip
          python -m pip install databricks-cli
        shell: powershell
        env:
          pythonLocation: C:\Users\Administrator\actions-runner\_work\_tool\Python\3.12.7\x64
          PKG_CONFIG_PATH: C:\Users\Administrator\actions-runner\_work\_tool\Python\3.12.7\x64/lib/pkgconfig
          Python_ROOT_DIR: C:\Users\Administrator\actions-runner\_work\_tool\Python\3.12.7\x64
          Python2_ROOT_DIR: C:\Users\Administrator\actions-runner\_work\_tool\Python\3.12.7\x64
          Python3_ROOT_DIR: C:\Users\Administrator\actions-runner\_work\_tool\Python\3.12.7\x64

      - name: Install azure-cli
  # You may pin to the exact commit or the version.
  # uses: pietrobolcato/install-azure-cli-action@9a10af1be5e3eb7931f48c0290364a131e7ecd7
        uses: pietrobolcato/install-azure-cli-action@v1.0.1
          


