name: learn-github-actions

on: [push]

jobs:
  setup-python:
    runs-on: 
      self-hosted
    
    steps:
      - uses: actions/checkout@v4

      - name: Install Python
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri https://www.python.org/ftp/python/3.10.0/python-3.10.0-amd64.exe -OutFile python-installer.exe
          Start-Process python-installer.exe -ArgumentList '/quiet InstallAllUsers=1 PrependPath=1' -Wait

      - name: Verify Python Installation
        shell: pwsh
        run: python --version
