name: learn-github-actions

on: [push]

jobs:
  setup-python:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.4

      - name: Set up Python
        uses: actions/setup-python@v5.2.0  # Specify the Python version you want to install

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: install-databricks-cli
        uses: microsoft/install-databricks-cli@v1.0.0


