name: Install Python on Windows VM

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  setup-python:
    runs-on: self-hosted
    name: Install Python
    # This specifies that the job will run on a self-hosted runner named "test"
    labels: [test]
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Install Python on Windows
        shell: pwsh
        run: |
          Invoke-WebRequest -Uri https://www.python.org/ftp/python/3.10.0/python-3.10.0-amd64.exe -OutFile python-installer.exe
          Start-Process python-installer.exe -ArgumentList '/quiet InstallAllUsers=1 PrependPath=1' -Wait
          
      - name: Verify Python Installation
        run: python --version
        shell: pwsh
