name: learn-github-actions

on: [push]

jobs:
  setup-python:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js environment
        uses: actions/setup-node@v4.0.4


      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Databricks CLI
        run: |
          python -m pip install --upgrade pip
          python -m pip install databricks-cli
        shell: powershell
        env:
          pythonLocation: C:\Users\Administrator\actions-runner\_work\_tool\Python\3.12.7\x64
          PKG_CONFIG_PATH: C:\Users\Administrator\actions-runner\_work\_tool\Python\3.12.7\x64/lib/pkgconfig
          Python_ROOT_DIR: C:\Users\Administrator\actions-runner\_work\_tool\Python\3.12.7\x64
          Python2_ROOT_DIR: C:\Users\Administrator\actions-runner\_work\_tool\Python\3.12.7\x64
          Python3_ROOT_DIR: C:\Users\Administrator\actions-runner\_work\_tool\Python\3.12.7\x64

      - name: Azure CLI Action
        uses: Azure/cli@v2.1.0

          
          


