name: Azure Data Factory CI/CD Pipeline

on:
  push:
    branches:
      - adf_publish
  workflow_dispatch:

jobs:
  # Continuous Integration (CI) Stage
  build:
    runs-on: self-hosted

    
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3


    # - name: Upload Build Artifact
    #   uses: actions/upload-artifact@v4.4.2
    #   with:
    #     name: ExportedArmTemplate
    #     path: ${{ github.workspace }}
    


      # Step 2: Copy all files to a staging directory
    - name: Copy files to artifact staging directory
      run: |
          # Define paths
          export SOURCE_DIR="${{ github.workspace }}"
          export TARGET_DIR="${{ github.workspace }}/artifact_staging"
          
          # Create the target directory
          mkdir -p $TARGET_DIR

          # Copy contents
          cp -r $SOURCE_DIR/* $TARGET_DIR/

      # Step 3: Upload the artifact to GitHub Actions (optional for local runner)
    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
          name: adf_publish_artifact
          path: artifact_staging/

      # Step 4: Save artifact on self-hosted runner for adf_publish branch
    - name: Save artifact locally on self-hosted runner
      if: github.ref == 'refs/heads/adf_publish'
      run: |
          # Create a local directory on the runner to save the artifact
          LOCAL_SAVE_DIR="${{ github.workspace }}/adf_publish_artifact"
          mkdir -p $LOCAL_SAVE_DIR
          
          # Copy artifact to the local directory
          cp -r artifact_staging/* $LOCAL_SAVE_DIR/    
      

  # Continuous Deployment (CD) Stage
  release:
    needs: build
    runs-on: self-hosted
    environment: production

    steps:
    - name: Download Build Artifact
      uses: actions/download-artifact@v4.1.8
      with:
        name: ExportedArmTemplate

            
    - name: Azure Login
      uses: azure/login@v2.2.0
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
        environment: AzureCloud
        audience: api://AzureADTokenExchange
        auth-type: SERVICE_PRINCIPAL

    - name: Azure PowerShell Pre-deployment
      uses: Azure/powershell@v1
      with:
        inlineScript: ${{ github.workspace }}\pre_post_deployment.ps1 -armTemplate "${{ github.workspace }}\ARMTemplateForFactory.json" -ResourceGroupName Anupam_rg -DataFactoryName prod-datafactory11 -predeployment $true -deleteDeployment $false
        azPSVersion: "latest"
        errorActionPreference: Stop

    - name: Deploy Azure Resource Manager (ARM) Template
      uses: Azure/arm-deploy@v2
      with:
        scope: 'resourcegroup'
        subscriptionId: '99705b85-b557-494c-bc4b-73e0ca27df77'
        resourceGroupName: 'Anupam_rg'
        template: ${{ github.workspace }}\ARMTemplateForFactory.json
        parameters: ${{ github.workspace }}\ARMTemplateParametersForFactory.json
        deploymentMode: Incremental
        deploymentName: adf-deployment
        additionalArguments: |
          -p factoryName=prod-datafactory11
          -p linkserviceAzureBlobStorage1_properties_typeProperties_serviceEndpoint="https://prodstg1232123.blob.core.windows.net/"

    - name: Azure PowerShell Post-deployment
      uses: Azure/powershell@v1
      with:
        inlineScript: ${{ github.workspace }}\pre_post_deployment.ps1 -armTemplate "${{ github.workspace }}\ARMTemplateForFactory.json" -ResourceGroupName Anupam_rg -DataFactoryName prod-datafactory11 -predeployment $false -deleteDeployment $true
        azPSVersion: "latest"
        errorActionPreference: Stop
